name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get Version from CHANGELOG
        id: changelog
        run: |
          # Ensure CHANGELOG.md exists
          if [ ! -f "CHANGELOG.md" ]; then
            echo "CHANGELOG.md not found!" >&2
            exit 1
          fi

          # Parse the first '##' line to extract the version
          VERSION=$(grep -oP '^## \K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -n 1)

          if [ -z "$VERSION" ]; then
            echo "No version found in CHANGELOG.md!" >&2
            exit 1
          fi

          echo "Parsed version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check for CHANGELOG Diff
        run: |
          if ! git diff --exit-code --name-only origin/main -- CHANGELOG.md; then
            echo "No changes detected in CHANGELOG.md. Please update the changelog." >&2
            exit 1
          fi

      - name: Configure Git
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          git config --global user.name "$AUTHOR_NAME"
          git config --global user.email "$AUTHOR_EMAIL"

      - name: Create Release Tag
        id: tag
        run: |
          TAG="${{ steps.changelog.outputs.version }}"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          generateReleaseNotes: true
          makeLatest: true
